'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
export default function AuthForm({ mode, initialRole='CUSTOMER' }) {
 const router=useRouter(); const isRegister=mode==='register';
 const [form,setForm]=useState({name:'',email:'',phone:'',password:'',role:initialRole==='VENDOR'?'VENDOR':'CUSTOMER',businessName:'',vendorType:'RETAILER'});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 function change(e){setForm(p=>({...p,[e.target.name]:e.target.value}));}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/auth/${isRegister?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed.');router.push('/dashboard');router.refresh();}catch(err){setError(err.message||'Something went wrong. Please try again.');}finally{setBusy(false);}}
 return <div className="auth-layout"><aside className="auth-aside"><span className="eyebrow"><i/> VERITAS AUTOS</span><h2>{isRegister?'Your parts business, better connected.':'Welcome back to the hub.'}</h2><p>{isRegister?'Create an account to shop parts, raise support tickets or apply to sell through Veritas Autos.':'Sign in to manage orders, contact support or access your vendor workspace.'}</p><ul><li>✓ Parts across passenger and commercial vehicles</li><li>✓ Support conversations handled by Veritas</li><li>✓ Vendor wallet and withdrawal requests</li></ul></aside><section className="panel"><span className="eyebrow red-eyebrow">{isRegister?'GET STARTED':'ACCOUNT ACCESS'}</span><h1 className="page-title">{isRegister?'Create your account':'Sign in'}</h1><p className="page-subtitle">{isRegister?'A few details to get you started.':'Enter your account details to continue.'}</p><form className="form-stack" onSubmit={submit}>{isRegister&&<><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={120} value={form.name} onChange={change} placeholder="Your full name"/></label><label>Phone number <span className="form-hint">Optional</span><input name="phone" autoComplete="tel" value={form.phone} onChange={change} maxLength={40} placeholder="+234..."/></label><label>Account type<select name="role" value={form.role} onChange={change}><option value="CUSTOMER">Customer</option><option value="VENDOR">Vendor / Seller</option></select></label>{form.role==='VENDOR'&&<><label>Business name<input name="businessName" value={form.businessName} onChange={change} required maxLength={180} placeholder="Registered or trading name"/></label><label>Vendor type<select name="vendorType" value={form.vendorType} onChange={change}><option value="RETAILER">Retailer</option><option value="WHOLESALER">Wholesaler</option></select></label><div className="notice">Vendor accounts require approval before products can appear in the marketplace. Customer contact is managed by Veritas Autos support.</div></>}</>}<label>Email address<input type="email" name="email" autoComplete="email" required value={form.email} onChange={change} maxLength={190} placeholder="you@example.com"/></label><label>Password<input type="password" name="password" autoComplete={isRegister?'new-password':'current-password'} required minLength={isRegister?10:1} maxLength={128} value={form.password} onChange={change} placeholder={isRegister?'At least 10 characters':'Your password'}/>{isRegister&&<span className="form-hint">Use at least 10 characters.</span>}</label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="button button-red" disabled={busy}>{busy?'Please wait…':isRegister?'Create account':'Sign in'} <span>↗</span></button><p className="form-hint">{isRegister?'Already registered?':'New to Veritas Autos?'} <Link className="text-link" href={isRegister?'/login':'/register'}>{isRegister?'Sign in':'Create an account'}</Link></p></form></section></div>
}
