import Link from 'next/link';
const categories = [
  ['Engine & Mechanical','Filters, belts, gaskets and engine components.','engine-mechanical','⚙'],
  ['Oil & Lubricants','Engine oils for petrol, diesel and commercial vehicles.','oil-lubricants','◉'],
  ['Braking','Brake pads, discs and stopping system components.','braking','◌'],
  ['Electrical','Batteries, alternators, lighting and electrical parts.','electrical','ϟ'],
  ['Suspension & Steering','Shocks, joints, mounts and steering components.','suspension-steering','↗'],
  ['Body Parts','Headlamps and replacement exterior components.','body-parts','◇'],
  ['Accessories','Useful accessories for everyday driving.','accessories','✳'],
  ['Tyres & Rims','Passenger tyres, truck tyres, alloy wheels and steel rims.','tyres-rims','◎'],
  ['Truck & Commercial Parts','Parts for HOWO, MACK, DAF and other heavy vehicles.','truck-commercial-parts','▰'],
];
const makes = ['Toyota','Mercedes Benz','Honda','Lexus','BMW','Hyundai','Kia','Nissan','Ford','Mazda','Mitsubishi','Peugeot','Volkswagen','HOWO','MACK','DAF'];
export default function Home() {
 return <><header className="site-header"><Link href="/" className="brand"><img src="/assets/veritas-autos-logo.png" alt="Veritas Autos"/><span>VERITAS <b>AUTOS</b><small>THE SPARE PARTS HUB</small></span></Link><nav className="desktop-nav"><a href="#categories">Shop parts</a><a href="#bulk">Bulk purchase</a><a href="#how">How it works</a><Link href="/support">Support</Link></nav><div className="header-actions"><Link className="header-link" href="/login">Sign in</Link><Link className="button button-red button-small" href="/register">Create account</Link></div></header>
 <main><section className="hero"><div className="hero-backdrop"/><div className="hero-content"><span className="eyebrow"><i/> ONE MARKETPLACE. EVERY JOURNEY.</span><h1>Find the part.<br/><em>Keep moving.</em></h1><p className="hero-lede">Your everyday hub for vehicle parts, oils, tyres, rims and heavy duty truck components. Find what you need from a growing network of automotive sellers.</p><form className="search-form" action="/shop"><span>⌕</span><input name="q" placeholder="Search a part, brand or part number" aria-label="Search parts"/><button type="submit">Search parts <b>↗</b></button></form><div className="hero-actions"><Link className="button button-red" href="/shop">Explore the marketplace <span>↗</span></Link><Link className="button button-outline" href="/register?role=VENDOR">Sell on Veritas</Link></div><div className="hero-proof"><div><b>Retail + wholesale</b><small>Parts for every scale</small></div><div><b>Support that stays involved</b><small>Help with orders and issues</small></div><div><b>Built for the trade</b><small>Drivers to fleet operators</small></div></div></div><div className="hero-image-wrap"><div className="hero-image-label"><span className="label-dot"/> YOUR VEHICLE. YOUR PARTS.<b>ONE PLACE.</b></div><img className="hero-car" src="/assets/hero-car.svg" alt="Vehicle illustration"/><div className="hero-image-foot"><span>VERITAS AUTOS</span><span>GENUINE PARTS. GREATER JOURNEYS.</span></div></div><div className="hero-index">01 <span/> BUILT FOR THE ROAD AHEAD</div></section>
 <div className="brand-rail"><span>PARTS FOR THE MAKES YOU KNOW</span>{makes.map(m=><b key={m}>{m.toUpperCase()}</b>)}</div>
 <section className="section category-section" id="categories"><div className="section-heading"><div><span className="eyebrow red-eyebrow">THE MARKETPLACE</span><h2>One hub for every<br/>part your vehicle needs.</h2></div><div className="section-intro"><p>Veritas Autos brings automotive parts, oils, tyres, rims and commercial truck components together in one place, with support from our team throughout the buying process.</p><Link href="/shop" className="text-link">Explore all categories <span>↗</span></Link></div></div><div className="category-grid">{categories.map(([name,desc,slug,icon])=><Link key={slug} href={`/shop?category=${slug}`} className="category-card"><div className="category-top"><span className="category-icon">{icon}</span><span className="category-arrow">↗</span></div><h3>{name}</h3><p>{desc}</p><div className="category-bottom">Explore category <span>→</span></div></Link>)}</div></section>
 <section className="vehicle-band"><div className="vehicle-copy"><span className="eyebrow">FIND PARTS THAT FIT</span><h2>Start with your<br/><em>vehicle.</em></h2><p>Choose a make and model to narrow your search to parts that match your vehicle.</p><Link href="/shop" className="button button-light">Find compatible parts <span>↗</span></Link></div><div className="vehicle-data"><div className="vehicle-data-head"><span>VEHICLE SELECTOR</span><span className="live-dot">● FITMENT SEARCH</span></div><div className="vehicle-selects"><label>Vehicle type<select defaultValue="passenger"><option value="passenger">Passenger vehicle</option><option value="truck">Truck & commercial</option></select></label><label>Make<select defaultValue=""><option value="" disabled>Select make</option>{makes.map(m=><option key={m}>{m}</option>)}</select></label><label>Model<select defaultValue="" disabled><option value="">Select make first</option></select></label><label>Year<select defaultValue=""><option value="">Select year</option>{Array.from({length:27},(_,i)=>2026-i).filter(y=>y>=2000).map(y=><option key={y}>{y}</option>)}</select></label></div><div className="vehicle-note"><span>ⓘ</span> Model options depend on the make you choose. The catalogue will continue to expand as vendors add verified fitment details.</div></div></section>
 <section className="bulk-section" id="bulk"><div className="bulk-copy"><span className="eyebrow red-eyebrow">FOR RETAILERS & FLEETS</span><h2>Buying for your store<br/>or your fleet?</h2><p>Explore bulk listings with minimum order quantities and clear stock information. Retailers can source from wholesalers without leaving the marketplace.</p><Link href="/shop?wholesale=true" className="button button-red">Browse bulk listings <span>↗</span></Link></div><div className="bulk-card"><div className="bulk-card-top"><span className="bulk-icon">▤</span><span className="bulk-tag">BULK PURCHASE</span></div><h3>Buy in volume.<br/><em>Plan with confidence.</em></h3><div className="bulk-metric"><span>Minimum order quantity</span><b>Shown on each listing</b></div><div className="bulk-metric"><span>Seller communication</span><b>Managed by Veritas support</b></div><div className="bulk-footer"><span>PARTS FOR THE TRADE</span><span>VA / 02</span></div></div></section>
 <section className="section how-section" id="how"><div className="how-head"><span className="eyebrow red-eyebrow">A CLEARER WAY TO SOURCE</span><h2>Simple for buyers.<br/>Clear for sellers.</h2></div><div className="how-grid"><article><span>01</span><h3>Find the right part</h3><p>Search by name, brand, category or vehicle. Compare listings and check the details before you order.</p></article><article><span>02</span><h3>Buy with confidence</h3><p>Our support team handles customer service, complaints and order enquiries. Vendors do not message customers directly.</p></article><article><span>03</span><h3>Grow your business</h3><p>Approved vendors manage their listings, track proceeds in a wallet and request withdrawals through the platform.</p></article></div></section>
 <section className="support-banner"><div><span className="eyebrow">HERE WHEN YOU NEED US</span><h2>Need a hand with an order?</h2><p>Start a private support conversation or raise a ticket and our team will help you follow it through.</p></div><div className="support-actions"><Link href="/support" className="button button-light">Contact support <span>↗</span></Link><Link href="/login" className="support-ticket-link">Open a support ticket →</Link></div></section></main>
 <footer className="site-footer"><div className="footer-top"><div className="footer-brand"><div className="brand footer-brand-lockup"><img src="/assets/veritas-autos-logo.png" alt=""/><span>VERITAS <b>AUTOS</b><small>THE SPARE PARTS HUB</small></span></div><p>Genuine parts. Greater journeys.</p></div><div className="footer-links"><div><b>Marketplace</b><Link href="/shop">Shop parts</Link><Link href="/shop?wholesale=true">Bulk purchase</Link><Link href="/register?role=VENDOR">Become a vendor</Link></div><div><b>Support</b><Link href="/support">Contact support</Link><Link href="/login">Support tickets</Link><Link href="/login">Account access</Link></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Veritas Autos. All rights reserved.</span><span>Genuine parts. Greater journeys.</span></div></footer></>;
}
