'use client';
import {useCallback,useEffect,useState} from 'react';
function useLoad(url){const [data,setData]=useState(null),[error,setError]=useState('');const reload=useCallback(async()=>{try{const r=await fetch(url,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load data');setData(d);setError('');}catch(e){setError(e.message||'Could not load data');}},[url]);useEffect(()=>{reload();},[reload]);return {data,error,reload};}
export default function AdminConsole(){const [tab,setTab]=useState('tickets'),tickets=useLoad('/api/tickets'),withdrawals=useLoad('/api/admin/withdrawals'),products=useLoad('/api/vendor/products'),[selectedTicket,setSelectedTicket]=useState(null),[ticketDetail,setTicketDetail]=useState(null),[reply,setReply]=useState(''),[chatList,setChatList]=useState([]),[conversationId,setConversationId]=useState(''),[chatMessages,setChatMessages]=useState([]),[chatReply,setChatReply]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const loadChat=useCallback(async(id='')=>{try{const r=await fetch('/api/chat'+(id?'?conversationId='+encodeURIComponent(id):''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Chat unavailable');setChatList(d.conversations||[]);if(id){setConversationId(id);setChatMessages(d.messages||[]);}else if(!conversationId&&d.conversations?.[0]){setConversationId(d.conversations[0].id);const x=await fetch('/api/chat?conversationId='+encodeURIComponent(d.conversations[0].id),{cache:'no-store'});const y=await x.json();setChatMessages(y.messages||[]);}}catch(e){setNotice(e.message);}},[conversationId]);
 useEffect(()=>{if(tab==='chat'){loadChat();const t=setInterval(()=>loadChat(conversationId||''),10000);return()=>clearInterval(t);}},[tab,conversationId,loadChat]);
 async function loadTicket(id){setSelectedTicket(id);try{const r=await fetch('/api/tickets/'+id,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setTicketDetail(d);}catch(e){setNotice(e.message);}}
 async function action(url,body,method='PATCH'){setBusy(true);setNotice('');try{const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed');setNotice('Update saved.');await Promise.all([tickets.reload(),withdrawals.reload(),products.reload()]);if(selectedTicket)await loadTicket(selectedTicket);if(tab==='chat')await loadChat(conversationId||'');}catch(e){setNotice(e.message||'Action failed');}finally{setBusy(false);}}
 async function sendTicketReply(e){e.preventDefault();if(!reply.trim()||!selectedTicket)return;await action('/api/tickets/'+selectedTicket,{message:reply},'POST');setReply('');}
 async function sendChatReply(e){e.preventDefault();if(!chatReply.trim()||!conversationId)return;await action('/api/chat',{message:chatReply,conversationId},'POST');setChatReply('');}
 return <section className="panel admin-console"><div className="console-tabs">{[['tickets','Support tickets'],['chat','Live support chat'],['products','Product review'],['withdrawals','Withdrawals']].map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{notice&&<div className="form-hint console-notice">{notice}</div>}
 {tab==='tickets'&&<div className="console-split"><div><h3 className="panel-title">Ticket queue</h3>{tickets.error&&<p className="form-error">{tickets.error}</p>}{(tickets.data?.tickets||[]).map(t=><button className={`queue-item ${selectedTicket===t.id?'active':''}`} key={t.id} onClick={()=>loadTicket(t.id)}><b>{t.ticket_number} · {t.subject}</b><span>{t.user_name||'Customer'} · {t.status}</span></button>)}{!tickets.data?.tickets?.length&&!tickets.error&&<p className="form-hint">No tickets found.</p>}</div><div>{ticketDetail?<><h3 className="panel-title">{ticketDetail.ticket.subject}</h3><p className="form-hint">{ticketDetail.ticket.ticket_number} · {ticketDetail.ticket.status} · {ticketDetail.ticket.category}</p><div className="message-list">{(ticketDetail.messages||[]).map(m=><article className="message-bubble" key={m.id}><b>{m.sender_name} · {m.sender_role}</b><p>{m.body}</p><small>{m.created_at}</small></article>)}</div><form className="inline-form" onSubmit={sendTicketReply}><input className="field" value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a response" required/><button className="button button-red" disabled={busy}>Reply</button></form><div className="inline-form status-actions">{['IN_PROGRESS','WAITING_ON_CUSTOMER','RESOLVED','CLOSED'].map(s=><button type="button" key={s} className="button button-outline-dark" onClick={()=>action('/api/admin/tickets/'+selectedTicket,{status:s})}>{s.replaceAll('_',' ')}</button>)}</div></>:<div className="empty-state">Select a ticket to review and respond.</div>}</div></div>}
 {tab==='chat'&&<div className="console-split"><div><h3 className="panel-title">Open conversations</h3>{chatList.map(c=><button className={`queue-item ${conversationId===c.id?'active':''}`} key={c.id} onClick={()=>loadChat(c.id)}><b>{c.user_name}</b><span>{c.user_role} · {c.user_email}</span></button>)}{!chatList.length&&<p className="form-hint">No open support conversations.</p>}</div><div><h3 className="panel-title">Support conversation</h3><div className="message-list">{chatMessages.map(m=><article className="message-bubble" key={m.id}><b>{m.sender_name} · {m.sender_role}</b><p>{m.body}</p><small>{m.created_at}</small></article>)}</div><form className="inline-form" onSubmit={sendChatReply}><input className="field" value={chatReply} onChange={e=>setChatReply(e.target.value)} placeholder="Reply as Veritas support" required disabled={!conversationId}/><button className="button button-red" disabled={busy||!conversationId}>Send</button></form><p className="form-hint">Messages are private between the account holder and Veritas Autos support.</p></div></div>}
 {tab==='products'&&<><h3 className="panel-title">Products awaiting review</h3><div className="table-wrap"><table><thead><tr><th>Product</th><th>Vendor</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{(products.data?.products||[]).filter(p=>p.status==='PENDING').map(p=><tr key={p.id}><td>{p.name}</td><td>{p.business_name||'Vendor'}</td><td>₦{Number(p.price).toLocaleString('en-NG')}</td><td><span className="status-pill warn">Pending</span></td><td><div className="table-actions"><button onClick={()=>action('/api/admin/products/'+p.id,{status:'ACTIVE'})}>Approve</button><button onClick={()=>action('/api/admin/products/'+p.id,{status:'REJECTED'})}>Reject</button></div></td></tr>)}</tbody></table></div>{products.error&&<p className="form-error">{products.error}</p>}</>}
 {tab==='withdrawals'&&<><h3 className="panel-title">Withdrawal requests</h3><div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Amount</th><th>Bank</th><th>Status</th><th>Actions</th></tr></thead><tbody>{(withdrawals.data?.withdrawals||[]).map(w=><tr key={w.id}><td>{w.business_name||w.vendor_name}</td><td>₦{Number(w.amount).toLocaleString('en-NG')}</td><td>{w.bank_name}<br/>{w.account_name}</td><td>{w.status}</td><td><div className="table-actions"><button onClick={()=>action('/api/admin/withdrawals/'+w.id,{status:'APPROVED',adminNote:''})}>Approve</button><button onClick={()=>action('/api/admin/withdrawals/'+w.id,{status:'PAID',adminNote:'Marked paid by admin'})}>Mark paid</button><button onClick={()=>action('/api/admin/withdrawals/'+w.id,{status:'REJECTED',adminNote:'Rejected by admin'})}>Reject</button></div></td></tr>)}</tbody></table></div>{withdrawals.error&&<p className="form-error">{withdrawals.error}</p>}</>}
 </section>;
}
